version: '3'

services:
  tygr:
    build:
      context: src/
      dockerfile: dockerfile
      #dockerfileで使用する変数を渡す。
      args:
        - http_tmp=$http_proxy
        - https_tmp=$https_proxy

    container_name: tygr_for_experimental

    volumes:
      - ./src:/src
    working_dir: /src

    #開発を行う為ひとまずinitを実行する。
    command: tail -f /dev/null

    #ttyとprivilegedを有効化
    privileged: true
    tty: true
    
    #学内用proxyを含めた環境変数ファイルを読込む
    env_file:
      - .env

    runtime: nvidia
    #core dumpを防ぐ為の設定
    shm_size: 12GB
    #コンテナネットワークの設定
    networks:
      - my_network

# コンテナネットワークの定義
networks:
  my_network:  
    driver: bridge