FROM nvidia/cuda:12.0.1-cudnn8-devel-ubuntu20.04

#docker-composeから環境変数を受け取る
ARG http_tmp 
ARG https_tmp

#コンテナに環境変数の設定を追加
ENV http_proxy=$http_tmp
ENV https_proxy=$https_tmp

#タイムゾーンを東京に設定
ENV TZ=Asia/Tokyo
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

#apt関連の設定
RUN apt update -y && apt upgrade -y

RUN apt install -y python3 python3-pip

RUN pip install torch==2.2.1 --extra-index-url https://download.pytorch.org/whl/cu128
