FROM nvidia/cuda:12.0.1-cudnn8-devel-ubuntu20.04

#docker-composeから環境変数を受け取る
ARG http_tmp 
ARG https_tmp

#コンテナに環境変数の設定を追加
ENV http_proxy=$http_tmp
ENV https_proxy=$https_tmp

#タイムゾーンを東京に設定
ENV TZ=Asia/Tokyo
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

#apt関連の設定
RUN apt update -y && apt upgrade -y
RUN apt install -y python3 python3-pip tmux

#torch関連のインストール
RUN pip install torch==1.9.1+cu102 torchvision==0.10.1+cu102 torchaudio==0.9.1 -f https://download.pytorch.org/whl/torch_stable.html
RUN pip install torch-scatter==2.0.8 -f https://data.pyg.org/whl/torch-1.9.1+cu102.html
RUN pip install torch-sparse==0.6.11 -f https://data.pyg.org/whl/torch-1.9.1+cu102.html
RUN pip install torch-geometric==1.7.2
